on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: docker
      uses: mosteo-actions/docker-run@v1
      with:
       image: ubuntu:18.04
       command: ls -l
