on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        echo "Start ...."
        pattern='\<N[O]COMMIT\>'
        echo "Check ..."
        output=`git log origin..HEAD`
        echo $output
        if [ -n "$output" ]; then
            printf 'forbidden pattern "%s" found:\n%s\n' "$pattern" "$output" >&2
            exit 1
        else
          echo "Else ..."
        fi
  
